# Generated by Django 5.1.1 on 2024-10-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tentfoodapp', '0004_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(default='Enter a name', max_length=30),
        ),
        migrations.AlterField(
            model_name='menubakery',
            name='name',
            field=models.CharField(default='Enter a name', max_length=30),
        ),
        migrations.AlterField(
            model_name='menuforeign',
            name='name',
            field=models.CharField(default='Enter a name', max_length=30),
        ),
        migrations.AlterField(
            model_name='menusnacks',
            name='name',
            field=models.CharField(default='Enter a name', max_length=30),
        ),
        migrations.AlterField(
            model_name='menuswallow',
            name='name',
            field=models.CharField(default='Enter a name', max_length=30),
        ),
    ]
