# Generated by Django 5.1.1 on 2024-10-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tentfoodapp', '0005_alter_menu_name_alter_menubakery_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menubakery',
            name='description',
            field=models.CharField(default='Describe your product', max_length=30),
        ),
        migrations.AlterField(
            model_name='menubakery',
            name='name',
            field=models.CharField(default='Enter a name', max_length=20),
        ),
        migrations.AlterField(
            model_name='menuforeign',
            name='description',
            field=models.CharField(default='Describe your product', max_length=30),
        ),
        migrations.AlterField(
            model_name='menuforeign',
            name='name',
            field=models.CharField(default='Enter a name', max_length=20),
        ),
        migrations.AlterField(
            model_name='menusnacks',
            name='description',
            field=models.CharField(default='Describe your product', max_length=30),
        ),
        migrations.AlterField(
            model_name='menusnacks',
            name='name',
            field=models.CharField(default='Enter a name', max_length=20),
        ),
        migrations.AlterField(
            model_name='menuswallow',
            name='description',
            field=models.CharField(default='Describe your product', max_length=30),
        ),
        migrations.AlterField(
            model_name='menuswallow',
            name='name',
            field=models.CharField(default='Enter a name', max_length=20),
        ),
    ]
